# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'




## => Site Settings
##############################
text_skin: dark # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
url: https://willguxy.github.io # the base hostname & protocol for your site e.g. https://www.someone.com
baseurl: # does not include hostname
title: think sauce
description: > # this means to ignore newlines until "Language & timezone"
  tech notes


## => Language and Timezone
##############################
lang: en # the language of your site, "en" (default, English), "zh"(简体中文), "zh-Hans"(简体中文), "zh-Hant"(繁體中文)
timezone: America/New_York # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values


## => Author and Social
##############################
author:
  # type:
  name: Will
  # url:
  # avator:
  # bio:
  email:  willgu@yahoo.com
  # facebook:  #your Facebook username
  twitter: shamroxk
  github: willguxy
  # linkedin:  #your Linkedin username
  # googleplus:  #your Google+ username
  # weibo:  yangmaoxiaozhan
  # douban:  #your Douban username


## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: willguxy/willguxy.github.io
repository_tree: master


## => Paths
##############################
paths:
  root: /
#  home: https://github.com/willguxy/willguxy.github.io/
#  archive:  /archive.html
#  rss:  /feed.xml


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->
excerpt_type: text # text (default), html

## license
license: CC-BY-NC-4.0

## TOC
toc:
  selectors: "h1,h2,h3" # "h1,h2,h3" (default)


## Markdown Enhancements
###################################
# Mathjax
mathjax: # false (default), true
mathjax_autoNumber: # false (default), true

# Mermaid
mermaid: # false (default), true

# Chart
chart: # false (default), true


## => Paginate
##############################
paginate: 10
paginate_path: /page:num # don't change this unless for special need


## => Sources
##############################
sources: # bootcdn (default), unpkg


## => Comments
##############################
comments:
  provider: "disqus"

  ## Disqus
  disqus:
    shortname: https-willguxy-github-io # the Disqus shortname for the site

  ## Gitalk
  # please refer to https://github.com/gitalk/gitalk for more info.
  #gitalk:
  #  clientID: # GitHub Application Client ID
  #  clientSecret: # GitHub Application Client Secret
  #  repository: # GitHub repo
  #  owner: # GitHub repo owner
  #  admin: # GitHub repo owner and collaborators, only these guys can initialize GitHub issues, IT IS A LIST.
      # - your GitHub Id


## => Pageview
##############################
pageview:
  provider: "leancloud"
    
  ## Leancloud
  leancloud:
    app_id: qCYcEXjnIST232dTXLooosC7-gzGzoHsz # LeanCloud App id
    app_key: kdGLIBDA7zFTPxrRNkuzqiir # LeanCloud App key
    app_class: counter # LeanCloud App class


## => Analytics
##############################
analytics:
  provider: false

  ## Google Analytics
  #google:
  #  ga_tracking_id: # Google Analytics id for the site
  #  ga_anonymize_ip: false # Anonymize IP tracking for Analytics


## => Build
##############################
markdown: kramdown
highlighter: rouge
permalink: date

exclude:
  - CHANGELOG.md
  - CHECKLIST.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: aritcle
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      pageview: true


## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
