# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'

text_color_theme: dark
## Base settings ##
url: https://willguxy.github.io #!the base hostname & protocol for your site e.g. https://www.someone.com (!!required!!)
baseurl: /
title: think sauce
description: > #this means to ignore newlines until "nav_lists:"
   tech notes

nav_lists:
  - titles:
      en:      About
      zh:      关于
      zh-Hans: 关于
      zh-Hant: 關於
    url: /about.html

## GitHub repository (if the site is hosted by GitHub) ##
repository: willguxy/willguxy.github.io
repository_tree: master

## Language & timezone ##
lang: zh #the language of your site, eg: en(English), zh(简体中文), zh-Hans(简体中文), zh-Hant(繁體中文)
timezone: America/New_York

## Author & social ##
author:
  name: Will
  email:  willgu@yahoo.com
  # facebook:  #your Facebook username
  twitter: shamroxk
  github: willguxy
  # googleplus:  #your Google+ username
  # weibo:  yangmaoxiaozhan
  # douban:  #your Douban username
  # linkedin:  #your Linkedin username

## TOC
toc:
  selectors: 'h1,h2,h3'

## Comment system (Disqus) ##
disqus:
  shortname: https-willguxy-github-io #the Disqus shortname for the site

## Google Analytics ##
# ga_tracking_id:  #Google analytics id for the site

## Reading quantity (LeanCloud) ##
leancloud:
  app_id: qCYcEXjnIST232dTXLooosC7-gzGzoHsz #LeanCloud App id
  app_key: kdGLIBDA7zFTPxrRNkuzqiir #LeanCloud App key
  app_class: counter #LeanCloud App class

# mathjax: true

## Paginate ##
paginate: 10
paginate_path: /blog/page:num

## Post excerpts ##
excerpt_separator: <!--more-->
excerpt_type: text ## text | html

## Build ##
markdown: kramdown
highlighter: rouge
permalink: date

exclude:
  - README.md
  - LICENSE
  - /vendor
  - /docs
  - /screenshots
  - /test

## Plugins ##
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji

## Server ##
server_url: "0.0.0.0"

## Development ##
isdebug: false
